import { chromium } from 'playwright';
import { readGedcom } from 'read-gedcom';
import { spawn } from 'node:child_process';
import { mkdtemp, readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
const dir = await mkdtemp(path.join(os.tmpdir(), 'geo-experience-'));
const data = JSON.parse(await readFile('data/overrides.json', 'utf8'));
data.newPersons.push({ id: 'qa-first', givenNames: 'Camille', surname: 'TESTEXPERIENCE', sex: 'U', birthDateRaw: '1 JAN 1900', notes: 'Première fiche' }, { id: 'qa-second', givenNames: 'Camille', surname: 'TESTEXPERIENCE', sex: 'U', birthDateRaw: '1 JAN 1900', notes: 'Seconde fiche' });
await writeFile(path.join(dir, 'overrides.json'), JSON.stringify(data));
const port = 3097; const base = `http://localhost:${port}`;
const env = { ...process.env, AUTH_PASSWORD: 'qa-admin', AUTH_SECRET: 'qa-only-local-secret', GEO_DATA_DIR: dir, AUTH_USERS_JSON: JSON.stringify([{ name: 'Lecture QA', role: 'reader', password: 'qa-reader' },{ name: 'Contribution QA', role: 'contributor', password: 'qa-contributor' }]) };
delete env.DATABASE_URL; delete env.POSTGRES_URL; delete env.VERCEL;
const server = spawn(process.execPath, ['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port',String(port)], { env, stdio: ['ignore', 'pipe', 'pipe'] });
let log = ''; server.stdout.on('data', b => log += b); server.stderr.on('data', b => log += b);
let browser;
try {
  for (let i=0; i<120; i++) { try { if ((await fetch(base+'/login')).ok) break; } catch {} if(i===119) throw new Error('Server did not start: '+log); await new Promise(r=>setTimeout(r,250)); }
  browser = await chromium.launch({headless:true, executablePath:process.env.QA_CHROMIUM || undefined, args: process.env.QA_CHROMIUM_ARGS ? JSON.parse(process.env.QA_CHROMIUM_ARGS) : undefined });
  const context = await browser.newContext({ viewport:{width:390,height:844} });
  await context.route(/https?:\/\/(?!localhost)/, r => r.abort());
  const page = await context.newPage(); page.setDefaultTimeout(15000); page.setDefaultNavigationTimeout(20000); const errors=[]; page.on('pageerror', e=>{errors.push(e.message);console.error('BROWSER ERROR', e.stack);});
  for(const route of ['/api/admin/debug-person','/api/admin/debug-journey','/api/journey/69','/api/persons']) assert.equal((await context.request.get(base+route)).status(),401,route);
  console.log('PASS anonymous data routes protected');
  await page.goto(base+'/login'); await page.locator('input[type=password]').fill('qa-admin'); await page.locator('button[type=submit]').click(); await page.waitForURL(base+'/');
  await page.getByRole('heading',{name:'Retrouvez votre place dans la famille'}).waitFor();
  const noOverflow = async () => assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth), 'Document overflows horizontally');
  await noOverflow(); await mkdir('/tmp/geonealogie-screens',{recursive:true}); await page.screenshot({path:'/tmp/geonealogie-screens/home-mobile.png'});
  await page.getByRole('button',{name:'Plus',exact:true}).click(); await page.getByRole('dialog').waitFor(); await page.getByRole('button',{name:'Fermer ×',exact:true}).click();
  const exportRes=await context.request.get(base+'/api/export/gedcom'); assert.equal(exportRes.status(),200); const gedcom=await exportRes.text(); assert.ok(gedcom.includes('0 TRLR')); assert.ok(gedcom.includes('TESTEXPERIENCE')); assert.ok(readGedcom(Buffer.from(gedcom)).getIndividualRecord().arraySelect().length >= 2);
  await page.goto(base+'/person/qa-first'); await page.getByRole('button',{name:'C’est moi / choisir comme point de départ'}).click(); await page.getByRole('status').filter({hasText:'mémorisé'}).waitFor();
  await page.getByRole('tab',{name:'Famille',exact:true}).click(); await page.getByRole('heading',{name:'Famille proche'}).waitFor(); await page.getByRole('tab',{name:'Sources',exact:true}).click();
  await page.getByText('Ajouter une source',{exact:true}).click(); await page.getByLabel('Événement concerné').fill('Naissance · 1 JAN 1900'); await page.getByLabel('Référence ou témoignage').fill('Acte de naissance — référence de test'); await page.getByLabel('Certitude',{exact:true}).selectOption('confirmed'); await page.getByRole('button',{name:'Enregistrer la source'}).click(); await page.getByText('Source enregistrée.',{exact:true}).waitFor(); const sourcedExport = await (await context.request.get(base+'/api/export/gedcom')).text(); assert.ok(sourcedExport.includes('Acte de naissance — référence de test')); assert.ok(readGedcom(Buffer.from(sourcedExport)).getIndividualRecord().arraySelect().length >= 2);
  await page.screenshot({path:'/tmp/geonealogie-screens/sources-mobile.png'});
  await page.goto(base+'/'); await page.getByRole('link',{name:'Explorer mes ancêtres'}).waitFor(); await page.getByRole('link',{name:'Reprendre mon exploration'}).waitFor();
  await page.setViewportSize({width:1440,height:1000}); await page.screenshot({path:'/tmp/geonealogie-screens/home-desktop.png'});
  await page.goto(base+'/person/qa-second'); await page.getByRole('link',{name:'Quel est mon lien avec cette personne ?'}).waitFor();
  console.log('PASS mobile navigation, personal reference, tabs, sources and export');
  await page.goto(base+'/tree'); await page.getByRole('button',{name:'Explorer Camille TESTEXPERIENCE',exact:true}).click(); await page.getByRole('dialog',{name:'Camille TESTEXPERIENCE'}).waitFor(); await page.getByRole('button',{name:'Centrer l’arbre',exact:true}).click(); await page.getByRole('button',{name:'Arbre en plein écran'}).click(); assert.equal(await page.locator('.tree-fullscreen').count(),1); await page.getByRole('button',{name:'Quitter le plein écran'}).click();
  await page.setViewportSize({width:390,height:844}); await noOverflow(); await page.screenshot({path:'/tmp/geonealogie-screens/tree-mobile.png'});
  await page.goto(base+'/person/qa-first/edit'); await page.locator('input[name=nickname]').fill('Surnom QA'); await page.getByRole('button',{name:'Enregistrer les modifications',exact:true}).click(); await page.waitForURL(base+'/person/qa-first');
  const detail=await (await context.request.get(base+'/api/persons/qa-first')).json(); assert.equal(detail.person.nickname,'Surnom QA');
  await page.goto(base+'/doublons'); 
  await page.locator('[data-pair="qa-first:qa-second"]').getByRole('button',{name:'Comparer avant de fusionner'}).click(); await page.getByRole('button',{name:'Confirmer la fusion'}).waitFor(); await page.getByRole('button',{name:'Confirmer la fusion'}).click(); await page.getByText('Fusion enregistrée.',{exact:false}).waitFor();
  assert.equal((await context.request.get(base+'/api/persons/qa-second')).status(),404);
  await page.goto(base+'/history'); await page.getByText('Annuler cette modification',{exact:true}).click(); await page.getByRole('button',{name:'Confirmer la restauration'}).click(); await page.getByText('Restauration effectuée.',{exact:true}).waitFor();
  assert.equal((await context.request.get(base+'/api/persons/qa-first')).status(),200); assert.equal((await context.request.get(base+'/api/persons/qa-second')).status(),200);
  console.log('PASS custom edit, comparison, merge and restoration');
  await browser.close();
  browser = await chromium.launch({headless:true, executablePath:process.env.QA_CHROMIUM || undefined, args:process.env.QA_CHROMIUM_ARGS ? JSON.parse(process.env.QA_CHROMIUM_ARGS) : undefined});
  const reader = await browser.newContext({viewport:{width:390,height:844}}); await reader.route(/https?:\/\/(?!localhost)/, r => r.abort()); const rp=await reader.newPage(); rp.setDefaultTimeout(15000); rp.setDefaultNavigationTimeout(20000); await rp.goto(base+'/login'); await rp.locator('input[type=password]').fill('qa-reader'); await rp.locator('button[type=submit]').click(); await rp.waitForURL(base+'/');
  assert.equal((await reader.request.get(base+'/history')).status(),403); assert.equal((await reader.request.post(base+'/api/admin/clear-cache')).status(),403); assert.equal((await reader.request.get(base+'/person/qa-first/edit')).status(),403);
  await rp.goto(base+'/person/qa-first'); await rp.getByRole('tab',{name:'Sources',exact:true}).click(); assert.equal(await rp.getByText('Ajouter une source',{exact:true}).count(),0);
  await rp.getByRole('button',{name:'Plus',exact:true}).click(); await rp.getByRole('button',{name:'Se déconnecter'}).click(); await rp.waitForURL(base+'/login');
  await reader.close();
  assert.deepEqual(errors,[]); console.log('PASS read-only access, logout, no browser errors');
} catch(e) { console.error(log.slice(-3500)); throw e; }
finally { await browser?.close(); server.kill(); await rm(dir,{recursive:true,force:true}); }
